<a href="https://colab.research.google.com/github/Olofmeister007/Pytorch-Prac/blob/main/00_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7,8],
                      [9, 10]])
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]] )
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0936, 0.5090, 0.8044, 0.9187],
        [0.9255, 0.3719, 0.6128, 0.6707],
        [0.8465, 0.9661, 0.5931, 0.6346]])

In [ ]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_image_size_tensor

tensor([[[0.9229, 0.5244, 0.7208],
         [0.3344, 0.9833, 0.0329],
         [0.1934, 0.5194, 0.1191],
         ...,
         [0.1915, 0.4058, 0.2190],
         [0.4085, 0.4811, 0.8954],
         [0.7030, 0.9029, 0.8503]],

        [[0.3791, 0.1218, 0.6228],
         [0.2699, 0.7701, 0.2595],
         [0.2554, 0.8336, 0.5314],
         ...,
         [0.2254, 0.5157, 0.0231],
         [0.1728, 0.6175, 0.4229],
         [0.6969, 0.4501, 0.8156]],

        [[0.6115, 0.9080, 0.7054],
         [0.7116, 0.4143, 0.9759],
         [0.5939, 0.9330, 0.4448],
         ...,
         [0.8400, 0.4340, 0.6690],
         [0.0126, 0.0366, 0.9961],
         [0.9405, 0.5748, 0.9482]],

        ...,

        [[0.8630, 0.6875, 0.6908],
         [0.9655, 0.8917, 0.2735],
         [0.4111, 0.2531, 0.0143],
         ...,
         [0.8429, 0.3723, 0.1959],
         [0.6815, 0.7324, 0.9701],
         [0.7645, 0.6569, 0.3676]],

        [[0.6893, 0.0763, 0.2761],
         [0.6136, 0.5063, 0.5562],
         [0.

In [ ]:
ones = torch.ones(3,4)
ones.dtype

torch.float32

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
meow = torch.arange(start=0, end=1000, step=77)
meow

haha = torch.zeros_like(input=meow)
haha

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
hoho = torch.zeros(3,4, dtype=None, device=None, requires_grad=False)