<a href="https://colab.research.google.com/github/Olofmeister007/Pytorch-Prac/blob/main/pytorch___2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


tensor = torch.tensor([1,2,3])
tensor + 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.02 ms, sys: 23 µs, total: 1.05 ms
Wall time: 3.46 ms


In [ ]:
%%time
torch.matmul(tensor,tensor)



CPU times: user 233 µs, sys: 0 ns, total: 233 µs
Wall time: 239 µs


tensor(14)

In [ ]:
A = torch.tensor([[1,2],
                 [3,4],
                 [5,6]])
B = torch.tensor([[7,10],
                 [8,11],
                 [9,12]])

torch.mean(A.type(torch.float32))











tensor(3.5000)

In [ ]:
X = torch.arange(0,15)
X.shape
X.reshape(3,5)

torch.stack([X,X,X], dim=1)


tensor([[ 0,  0,  0],
        [ 1,  1,  1],
        [ 2,  2,  2],
        [ 3,  3,  3],
        [ 4,  4,  4],
        [ 5,  5,  5],
        [ 6,  6,  6],
        [ 7,  7,  7],
        [ 8,  8,  8],
        [ 9,  9,  9],
        [10, 10, 10],
        [11, 11, 11],
        [12, 12, 12],
        [13, 13, 13],
        [14, 14, 14]])

In [ ]:
X=torch.unsqueeze(X,dim=0)
X


tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [ ]:
img= torch.rand(size=(224,224,3))

img = torch.permute(img,(2,0,1))
img.shape

torch.Size([3, 224, 224])

In [ ]:
Y = torch.arange(1,10).reshape(1,3,3)

Y



tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
Y[:,:,1] #all values of 0 and 1 dim but only 1 values of 2nd dimension

tensor([[2, 5, 8]])

In [ ]:
Y[:,1,1]

tensor([5])